version: "3.7"
services:

  front-envoy:
    extra_hosts:
      # Replace the line below if you run your container on Windows/Mac only
      # - "emulator:host.docker.internal"
      - "emulator:172.17.0.1"
    build:
      context: .
      dockerfile: envoy.Dockerfile
    networks:
      - envoymesh
    expose:
      - "8080"
      - "8001"
      - "8443"
    ports:
      - "80:8080"
      - "443:8443"
      - "8001:8001"

  nginx:
    build:
      context: ..
      dockerfile: docker/nginx.Dockerfile
    networks:
      envoymesh:
        aliases:
          - nginx
    expose:
      - "80"


networks:
  envoymesh: {}