os: Visual Studio 2015

matrix:
  fast_finish: true

platform:
  - x86
  - x64

configuration:
  - Debug
  - Release

clone_folder: c:\projects\libwebrtc

before_build:
  - cd c:\projects\libwebrtc
  - if "%platform%"=="x86" set CMAKE_GENERATOR_NAME=Visual Studio 14 2015
  - if "%platform%"=="x64" set CMAKE_GENERATOR_NAME=Visual Studio 14 2015 Win64
  - cmake -G "%CMAKE_GENERATOR_NAME%" -DBUILD_SAMPLE=1 -DCMAKE_BUILD_TYPE=%configuration% -DCMAKE_INSTALL_PREFIX=c:\projects\libwebrtc .

build:
  project: PACKAGE.vcxproj

artifacts:
  - path: libwebrtc-*.zip
    name: Releases

deploy:
  provider: GitHub
  auth_token:
    secure: QQrYk1F7DLgQ9eht+J6hvDiDRu8a+AKKwsOetybrL8B32UYxlNJKSZIpD0yHPVsx
  artifact: /libwebrtc-.*\.zip/
  draft: false
  prerelease: false
  on:
    appveyor_repo_tag: true

test: off
